### ISSUE TITLE
sample script aiwoof.py should show an error message if -h and -p are not specified.

### ISSUE THREAD

**Issue by caranha** [ehauckdo/AIWoof#2]
You can probably use the python option parsing library to detect whether the -h and -p options have been specified or not.

**Comment by ehauckdo** [comment]
Fixed in 6c22aabfa9b9418e47e06dd923db59feeb5574bb

There is argument parsing code inside Harada's tcpipclient_parsed.py, but I had my own parsing in the agent's script file. I'm avoiding making changes there so there are no compatibility problems later on.
